<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="Assets\Fonts\DejaVuSans.ttf">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
        <PackageReference Include="Minio" Version="6.0.5" />
        <PackageReference Include="Nethereum.Web3" Version="6.1.0" />
        <PackageReference Include="QuestPDF" Version="2024.12.3" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.7" />
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.12.1" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\EduVote.Application\EduVote.Application.csproj" />
        <ProjectReference Include="..\EduVote.DAL.Postgresql\EduVote.DAL.Postgresql.csproj" />
    </ItemGroup>

</Project>
